apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    service: django
spec:
  ports:
  - port: 8080
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  selector:
    service: django

