apiVersion: apps/v1 # 
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nargessalehi98/private-note-nginx:1.0.1
        ports:
        - containerPort: 80
