apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.back.fullnameOverride }}
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.back.fullnameOverride }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetCPUUtilizationPercentage: {{ .Values.back.autoscaling.targetCPUUtilizationPercentage }}