# Generated by Django 4.0.5 on 2022-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=100)),
                ('url', models.CharField(max_length=10)),
                ('expired_date', models.DateTimeField()),
            ],
        ),
    ]
