# Generated by Django 4.0.5 on 2022-06-24 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_alter_notes_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 8, 49, 4, 828937, tzinfo=utc)),
        ),
    ]
