apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    service: back
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer
  selector:
    service: back

